### PR TITLE
Avatar badge

### PR DESCRIPTION
**Pull request by Tejinder15**
### Avatar Component
image

### Badge Component
image

### CODE REVIEW

**Review by mohammed-sas — APPROVED** [review]
awesome ui . suggestion : replace all color related properties with css variables . your code is good to merge

**Review by Prathyusha-96 — COMMENTED** [review]
looks great

**Review by Prathyusha-96 — APPROVED** [review]

**Comment by AnkurChunekar** [comment]
Great work Tejindar, keep going!

**Review by AnkurChunekar — APPROVED** [review]

**Review by Sudhanshusoni45 — APPROVED** [review]
Nice Work, looks good !

**Pull request merged**
