### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Tejinder15**
## i Have made some changes

CSB LInk
https://biybc.csb.app/

### CODE REVIEW

**Review by VishalPatil18 — APPROVED** [review]
The code looks good. Just one suggestion on the UI part is that you could make these underlines a bit faint as suggested by Pranshu also as that helps in better UI.
Currently as they are quite dark they take away the attention of the user.

Screenshot 2022-02-05 at 16 53 07

**Comment by VishalPatil18** [comment]
Also, have you made the site responsive or is it left to do?

**Comment by Tejinder15** [comment]
@VishalPatil18  but in my system the lines are not that dark

**Review by Abhijeet43 — APPROVED** [review]

**Comment by VishalPatil18** [comment]
> @VishalPatil18 but in my system the lines are not that dark

Ok then it's fine. I was referring to something like [this](https://semantic-ui.com/introduction/getting-started.html) website has.

**Review by VishalPatil18 — APPROVED** [review]
Looks much better now!

**Comment by Tejinder15** [comment]
> Looks much better now!

can you please send screenshot

**Review by NagaSatyaGeeth — APPROVED** [review]

**Pull request merged**
